version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cruddb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "5000:80"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"